# Q1

In [2]:
import numpy as np
import matplotlib.pyplot as plt


class Hopfield_Class:
    def __init__(self, dim):
        self.weights = np.zeros((dim, dim))

    def Check(self, inp):
        inp = np.array(inp)
        inp_sign = np.sign(np.dot(self.weights, inp))

        if ((inp_sign == inp).all()):
            print(inp, "is stable")
        else:
            print(inp, "is not stable, The closest saved stable data  is: ", inp_sign)

    def Store(self, inp_list):

        inp_list = np.array(inp_list)
        new_weights = inp_list * inp_list.reshape(-1, 1)
        np.fill_diagonal(new_weights, 0)
        self.weights += new_weights
        print("Weights after being updated by--> ", inp_list, "is changed to --> :\n", self.weights)


if __name__ == '__main__':
    ####part 1

    hf = Hopfield_Class(8)
    hf.Store([-1, -1, 1, -1, 1, -1, -1, 1])
    hf.Store([-1, -1, -1, -1, -1, 1, -1, -1])
    hf.Store([-1, 1, 1, -1, -1, 1, -1, 1])
    print("***part 1 ended***")

    ####part 2

    hf.Check([-1, -1, 1, -1, 1, -1, -1, 1])
    hf.Check([-1, -1, -1, -1, -1, 1, -1, -1])
    hf.Check([-1, 1, 1, -1, -1, 1, -1, 1])
    print("***part 2 ended***")

    ####part 3

    hf.Check([1, -1, 1, -1, 1, -1, -1, 1])
    hf.Check([1, 1, -1, -1, -1, 1, -1, -1])
    hf.Check([1, 1, 1, -1, 1, 1, -1, 1])
    print("***part 3 ended***")

Weights after being updated by-->  [-1 -1  1 -1  1 -1 -1  1] is changed to --> :
 [[ 0.  1. -1.  1. -1.  1.  1. -1.]
 [ 1.  0. -1.  1. -1.  1.  1. -1.]
 [-1. -1.  0. -1.  1. -1. -1.  1.]
 [ 1.  1. -1.  0. -1.  1.  1. -1.]
 [-1. -1.  1. -1.  0. -1. -1.  1.]
 [ 1.  1. -1.  1. -1.  0.  1. -1.]
 [ 1.  1. -1.  1. -1.  1.  0. -1.]
 [-1. -1.  1. -1.  1. -1. -1.  0.]]
Weights after being updated by-->  [-1 -1 -1 -1 -1  1 -1 -1] is changed to --> :
 [[ 0.  2.  0.  2.  0.  0.  2.  0.]
 [ 2.  0.  0.  2.  0.  0.  2.  0.]
 [ 0.  0.  0.  0.  2. -2.  0.  2.]
 [ 2.  2.  0.  0.  0.  0.  2.  0.]
 [ 0.  0.  2.  0.  0. -2.  0.  2.]
 [ 0.  0. -2.  0. -2.  0.  0. -2.]
 [ 2.  2.  0.  2.  0.  0.  0.  0.]
 [ 0.  0.  2.  0.  2. -2.  0.  0.]]
Weights after being updated by-->  [-1  1  1 -1 -1  1 -1  1] is changed to --> :
 [[ 0.  1. -1.  3.  1. -1.  3. -1.]
 [ 1.  0.  1.  1. -1.  1.  1.  1.]
 [-1.  1.  0. -1.  1. -1. -1.  3.]
 [ 3.  1. -1.  0.  1. -1.  3. -1.]
 [ 1. -1.  1.  1.  0. -3.  1.  1.]
 [-1.  1. -1. -1.